function L = gibbs_loglik(Adk,Bkw,Mk,...
        I,D,K,W,di,wi,ci,citest,Id,Iw,Nd,alpha,beta);

% the log joint probability directly from the formula (see part e) of the
% assignment pdf).
L = D * log(gamma(K * alpha)) - sum(log(gamma(K * alpha + sum(Adk,2)))) + ...
        sum(sum(log(gamma(alpha + Adk)))) - D * K * log(gamma(alpha)) + ...
            K * log(gamma(W * beta)) - sum(log(gamma(W * beta + Mk))) + ...
                sum(sum(log(gamma(beta + Bkw)))) - K * W * log(gamma(beta));
